# The directory containing the source files to parse recursively
source:
- ./app/styles/base
- ./app/styles/layout
- ./app/styles/components
- ./app/styles/animations

# The directory that aigis will build to
dest: ./styleguide

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./aigis_assets
  - ./app/fonts
  - ./app/images
  - ./app/styles/main.css
  - ./app/styles/_variables.json
  - ./bower_components
  - ./app/scripts/main.js

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./template_ejs
template_engine: ejs
color_palette: false

name: Acadia Styleguide
